### ISSUE TITLE
Lazy loading words if list goes more than 10 words.

### ISSUE THREAD

**Issue by shreyas-a** [shreyas-a/wordly#4]

**Comment by abhishek1nair** [comment]
@shreyas-a Installed the extension in dev mode as specified in the README, but my extension is stuck on loading screen, any idea why it would be happening? would really like to work on this issue.

**Comment by abhishek1nair** [comment]
ok working now, will continue with implementation.

**Comment by abhishek1nair** [comment]
@shreyas-a I read the `sync` api doc and it seems that it only stores objects and `get` returns the whole requested object. Only implementation I can think of is you store separate chunks in the `sync` storage per 10 items and load them in the same way. But this would require changing your current implementation. And how would it affect existing users? Love to know your thoughts!

**Comment by villevpe** [comment]
I'm sorry I didn't update anything to the issue but I already have a PR opened for this ( #8 ). For the record @abhishek1nair you are right about the sync API, basically it is not any means useful to implement the lazy loading into the store because it is all local data (that's why the api is synchronous in nature). 

From the UX side however it is important not to render all the words to the popup instantly because that would deteriorate both performance and usability if there are lots of words to render. Rendering more words should be done in chunks when users scrolls for more content or alternatively with a "show more" button if that's a more preferred way.
